
package com.example.ws.server3.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JPAServer", targetNamespace = "http://services.server3.ws.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JPAServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.ws.server3.services.UserInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserInfo", targetNamespace = "http://services.server3.ws.example.com/", className = "com.example.ws.server3.services.GetUserInfo")
    @ResponseWrapper(localName = "getUserInfoResponse", targetNamespace = "http://services.server3.ws.example.com/", className = "com.example.ws.server3.services.GetUserInfoResponse")
    public UserInfo getUserInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
