
package com.example.ws.server3.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserServicesImplService", targetNamespace = "http://services.server3.ws.example.com/", wsdlLocation = "http://10.60.150.151:8889/services/UserInfoServices?wsdl")
public class UserServicesImplService
    extends Service
{

    private final static URL USERSERVICESIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERSERVICESIMPLSERVICE_EXCEPTION;
    private final static QName USERSERVICESIMPLSERVICE_QNAME = new QName("http://services.server3.ws.example.com/", "UserServicesImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.60.150.151:8889/services/UserInfoServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERSERVICESIMPLSERVICE_WSDL_LOCATION = url;
        USERSERVICESIMPLSERVICE_EXCEPTION = e;
    }

    public UserServicesImplService() {
        super(__getWsdlLocation(), USERSERVICESIMPLSERVICE_QNAME);
    }

    public UserServicesImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERSERVICESIMPLSERVICE_QNAME, features);
    }

    public UserServicesImplService(URL wsdlLocation) {
        super(wsdlLocation, USERSERVICESIMPLSERVICE_QNAME);
    }

    public UserServicesImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERSERVICESIMPLSERVICE_QNAME, features);
    }

    public UserServicesImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserServicesImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JPAServer
     */
    @WebEndpoint(name = "JPAServerPort")
    public JPAServer getJPAServerPort() {
        return super.getPort(new QName("http://services.server3.ws.example.com/", "JPAServerPort"), JPAServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JPAServer
     */
    @WebEndpoint(name = "JPAServerPort")
    public JPAServer getJPAServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.server3.ws.example.com/", "JPAServerPort"), JPAServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERSERVICESIMPLSERVICE_EXCEPTION!= null) {
            throw USERSERVICESIMPLSERVICE_EXCEPTION;
        }
        return USERSERVICESIMPLSERVICE_WSDL_LOCATION;
    }

}
