
package com.ylk.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerImpl", targetNamespace = "http://webservices.ylk.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://webservices.ylk.com/", className = "com.ylk.webservices.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://webservices.ylk.com/", className = "com.ylk.webservices.AddResponse")
    @Action(input = "http://webservices.ylk.com/ServerImpl/addRequest", output = "http://webservices.ylk.com/ServerImpl/addResponse")
    public double add(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
